### ISSUE TITLE
changing code, log names

### ISSUE THREAD

**Issue by paolap** [aus-ref-clim-data-nci/OISST#1]
Just checked the code and it looks great,  just a really minor issue, you wouldn't have known about but we decided to be as uniform as possible in the file naming, so code should be

<dataset>.py/sh in this case just oisst.py

and update log is update_log.txt

for concat having oisst_concat.py and concat_log.txt is fine, finally also add the logs to the repo :-)

**Comment by greensh16** [comment]
Ok I've done this now, thanks for letting me know about that.
